### ISSUE TITLE
Can't select APK on Android 12 and up

### ISSUE THREAD

**Issue by AndnixSH** [TimScriptov/ApkSignatureKill#4]
I encountered an issue selecting APK on Android 12 and up that I don't know how to fix them

1. File picker can't see any apk files even they are present

2. When inputting the apk path manually, the app instantly crashes, throwing this error. 

```
Process: com.mcal.apksignkill, PID: 9590
java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference in method 'void com.mcal.apksignkill.utils.MyAppInfo.<init>(android.content.Context, java.lang.String)'
	at com.mcal.apksignkill.utils.MyAppInfo.<init>(MyAppInfo.java:25)
	at com.mcal.apksignkill.fragments.HomeFragment$1.afterTextChanged(HomeFragment.java:93)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:12365)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:15851)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1278)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:314)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:304)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)
	at android.view.inputmethod.BaseInputConnection.replaceTextInternal(BaseInputConnection.java:1026)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:962)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:241)
	at com.android.internal.inputmethod.EditableInputConnection.commitText(EditableInputConnection.java:222)
	at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:207)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$commitText$16(RemoteInputConnectionImpl.java:630)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$DuD803urSTti1OmMx2Hq0yX1sSU(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda15.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by timscriptov** [comment]
You need to rewrite the application code, it is very outdated

**Comment by timscriptov** [comment]
Google recommended use SAF

**Comment by AndnixSH** [comment]
Ok, I see
